plugins{
    /* L'ancienne écriture :
        apply plugin: 'java'
        apply plugin: 'war'*/
    id 'java' // signifie le module server est un projet Java
    id 'war'  // Gradle sait construire une appli web Java
}

java{ // configure le plugin Java chargé ci-dessus
    toolchain{
        languageVersion = JavaLanguageVersion.of(17) // Pour compiler ce projet Java, je demande un JDK Java 17
    }
}

repositories {
    mavenCentral() // Lorsque j’ai besoin d’une bibliothèque Java externe, cherche-la dans Maven Central. Maven Central est essentiellement un grand dépôt de bibliothèques Java. (ici utile pour JUnit)
}

dependencies {
    // JUnit est nécessaire pour compiler/exécuter mes tests, mais pas pour mon application finale.
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Anicennement : providedCompile "javax:javaee-api:8.0.1"
    compileOnly 'javax:javaee-api:8.0.1' // Wildfly fournit lui même les implémentations JavaEE
}

test{
    useJUnitPlatform() // utilise la plateforme JUnit pour découvrir et lancer mes tests.
}